### ISSUE TITLE
Importing is breaking for me

### ISSUE THREAD

**Issue by gbinal** [project-open-data/catalog-generator#6] opened 2013-01-28 19:27 UTC
I'm attempting to use a test .csv to test the import (and conversion process) but have hit multiple failures.  

A)  I launch the generator.  I press Import and choose the sample .csv.  On the resulting mapping page, the list of core metadata is duplicated multiple times - it would seem once for each row in the CSV.  
![catalog generator 2](https://f.cloud.github.com/assets/633088/104258/5728f29e-697e-11e2-9629-27a65602dfb9.JPG)

B) After clicking Import to move on from the mapping page, the results are muxed up, with sections of empty fields and the creation of other data sets named 'Dataset'.  It's worth seeing to recreate.

**Comment by benbalter** [comment] 2013-02-06 20:57
Closing as duplicate of #8 and #7

**Closed as completed by benbalter** 2013-02-06 20:57 UTC
